import { _electron as electron, expect } from '@playwright/test';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { parseEnv } from 'node:util';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Uses the existing backend and an isolated MySQL test database, never a mock login.
const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const serverRoot = path.resolve(root, '../server');
const envFile = parseEnv(await readFile(path.join(serverRoot, '.env'), 'utf8'));
const databaseUrl = process.env.TEST_DATABASE_URL || envFile.TEST_DATABASE_URL;
if (!databaseUrl?.startsWith('mysql://') || !new URL(databaseUrl).pathname.endsWith('_test')) throw new Error('TEST_DATABASE_URL must point to a migrated MySQL database ending in _test.');
const requireServer = createRequire(path.join(serverRoot, 'package.json'));
const { PrismaClient } = requireServer('@prisma/client');
const { createApp } = await import('../../server/dist/app.js');
const { loadConfig } = await import('../../server/dist/config.js');
const db = new PrismaClient({ datasources: { db: { url: databaseUrl } } });
const { app, auth, realtime } = createApp(db, loadConfig({ NODE_ENV: 'test', DATABASE_URL: databaseUrl }), { async send() {} });
const server = createServer(app);
const email = `desktop-${randomUUID()}@example.com`;
const password = 'desktop-test-password!';
let desktop;
try {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const env = { ...process.env, MARIONET_BE_URL: `http://127.0.0.1:${server.address().port}` };
  delete env.ELECTRON_RUN_AS_NODE;
  delete env.MARIONET_DEV_URL;
  desktop = await electron.launch({ args: ['.', '--enable-logging=stderr', `--user-data-dir=${path.join(root, '.local', 'desktop-test-profile')}`], cwd: root, env });
  const page = await desktop.firstWindow();
  const settled = () => expect(page.locator('.page-view[inert]')).toHaveCount(0);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await expect(page.getByRole('button', { name: '로그인', exact: true })).toBeVisible();
  await page.evaluate(() => document.fonts.ready);
  await mkdir(path.join(root, '.local'), { recursive: true });
  await page.screenshot({ path: path.join(root, '.local/login-desktop.png') });
  await page.getByRole('button', { name: '회원가입', exact: true }).click();
  await settled();
  await expect(page.getByRole('heading', { name: '마리오넷 회원가입' })).toBeVisible();
  await page.screenshot({ path: path.join(root, '.local/signup-desktop.png') });
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(920, 640));
  await expect(page.getByRole('button', { name: '계정 만들기', exact: true })).toBeInViewport();
  await page.screenshot({ path: path.join(root, '.local/signup-compact.png') });
  await page.getByRole('button', { name: '계정 만들기', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('이메일');
  await page.getByLabel('이메일', { exact: true }).fill(email);
  await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByLabel('비밀번호 확인', { exact: true }).fill('different-password');
  await page.getByRole('button', { name: '계정 만들기', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('일치하지');
  expect(await db.user.count({ where: { email } })).toBe(0);
  await page.getByLabel('비밀번호 확인', { exact: true }).fill(password);
  await page.getByRole('button', { name: '계정 만들기', exact: true }).click();
  await expect(page.getByRole('heading', { name: '가입을 환영해요!' })).toBeVisible();
  await settled();
  expect(await page.evaluate(() => window.marioNet.getSession())).toBeNull();
  await page.getByRole('button', { name: '로그인하러 가기' }).click();
  await settled();
  await expect(page.getByLabel('이메일', { exact: true })).toHaveValue(email);
  await expect(page.getByLabel('비밀번호', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: '회원가입', exact: true }).click();
  await settled();
  await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByLabel('비밀번호 확인', { exact: true }).fill(password);
  await page.getByRole('button', { name: '계정 만들기', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('이미 가입된');
  await page.getByRole('button', { name: '로그인으로 돌아가기', exact: true }).click();
  await settled();
  await expect(page.getByLabel('이메일', { exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(root, '.local/login-compact.png') });
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1400, 850));
  await page.getByLabel('이메일', { exact: true }).fill('');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('이메일');
  await page.getByLabel('이메일', { exact: true }).fill(email);
  await page.getByLabel('비밀번호', { exact: true }).fill('incorrect-password!');
  await page.getByRole('button', { name: '비밀번호 표시', exact: true }).click();
  await expect(page.getByLabel('비밀번호', { exact: true })).toHaveAttribute('type', 'text');
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('올바르지');
  await page.getByLabel('비밀번호', { exact: true }).fill(password);
  await page.getByLabel('비밀번호', { exact: true }).press('Enter');
  await expect(page.getByRole('heading', { name: /^노드 관제/ })).toBeVisible();
  await settled();
  await expect(page.getByRole('heading', { name: '첫 번째 Node를 연결해보세요' })).toBeVisible();
  await page.screenshot({ path: path.join(root, '.local/dashboard-empty.png') });
  const owner = await db.user.findUniqueOrThrow({ where: { email } });
  await db.node.createMany({ data: [1,2,3,4,5].map(index => ({ userId: owner.id, name: `Test PC ${index}`, platform: 'windows', keyHash: 'a'.repeat(64) })) });
  await page.getByRole('button', { name: 'Node 새로고침' }).click();
  const firstNode = page.getByRole('button', { name: 'Test PC 1 선택', exact: true });
  await expect(firstNode).toBeVisible();
  await firstNode.click();
  await expect(firstNode).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('switch', { name: '노드 선택 열림' }).click();
  await expect(firstNode).toBeDisabled();
  await expect(page.getByRole('button', { name: '선택 해제', exact: true })).toBeDisabled();
  await page.getByRole('switch', { name: '노드 선택 열림' }).click();
  await page.getByLabel('Node 이름 검색').fill('PC 2');
  await expect(page.getByRole('button', { name: 'Test PC 2 선택', exact: true })).toBeVisible();
  await expect(firstNode).toHaveCount(0);
  await page.getByLabel('Node 이름 검색').fill('');
  await page.getByRole('button', { name: '프리셋 추가', exact: true }).click();
  await page.getByLabel('프리셋 이름').fill('광클');
  const iconPath = path.join(root, '.local', 'test-icon.png');
  await writeFile(iconPath, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aN9sAAAAASUVORK5CYII=', 'base64'));
  await page.getByLabel('프리셋 아이콘 업로드').setInputFiles(iconPath);
  await expect(page.getByAltText('선택한 프리셋 아이콘')).toBeVisible();
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await expect(page.getByRole('button', { name: '광클', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '프리셋 수정', exact: true }).click();
  await page.getByLabel('프리셋 이름').fill('테스트 프리셋');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await expect(page.getByRole('button', { name: '테스트 프리셋', exact: true })).toBeVisible();
  await page.screenshot({ path: path.join(root, '.local/dashboard-desktop.png') });
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(920, 640));
  await expect(page.getByRole('button', { name: '로그아웃' })).toBeInViewport();
  await expect(page.getByRole('button', { name: '프리셋 추가', exact: true })).toBeInViewport();
  await page.screenshot({ path: path.join(root, '.local/dashboard-compact.png') });
  await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1400, 850));
  const session = await page.evaluate(() => window.marioNet.getSession());
  expect(Object.keys(session).sort()).toEqual(['expiresAt', 'user']);
  expect(await page.evaluate(() => typeof window.require)).toBe('undefined');
  expect(await page.evaluate(() => typeof window.process)).toBe('undefined');
  expect(await page.evaluate(() => localStorage.length)).toBe(0);
  await page.reload();
  await expect(page.getByRole('heading', { name: /^노드 관제/ })).toBeVisible();
  await expect(page.getByRole('button', { name: '테스트 프리셋', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '프리셋 삭제', exact: true }).click();
  await page.getByRole('button', { name: '삭제', exact: true }).click();
  await expect(page.getByRole('button', { name: '테스트 프리셋', exact: true })).toHaveCount(0);
  expect(errors).toEqual([]);
  await page.screenshot({ path: path.join(root, '.local/login-success.png') });
  await page.getByRole('button', { name: '로그아웃', exact: true }).click();
  await expect(page.getByRole('button', { name: '로그인', exact: true })).toBeVisible();
  await settled();
  expect(await page.evaluate(() => window.marioNet.getSession())).toBeNull();
  await desktop.close(); desktop = null;
  const sessions = await db.session.findMany({ where: { user: { email } } });
  expect(sessions.length).toBe(1);
  expect(sessions[0].revokedAt).not.toBeNull();
  console.log('Desktop integration passed: signup/login, dashboard, node search and selection lock, preset image upload/CRUD/persistence, compact layout, token isolation and logout.');
} finally {
  if (desktop) await desktop.close();
  await realtime.stop();
  await new Promise(resolve => server.close(resolve));
  await db.user.deleteMany({ where: { email } });
  await db.$disconnect();
}
